[package]
name = "stats"
version = "0.1.0"
edition = "2021"

[dependencies]
num-format = "0.4.4"

# TODO - enable this when wasm is disabled
comfy-table = { version = "7.1.1", default-features = false }
