[package]
name = "catalog_schema_mocks"
version = "0.1.0"
edition = "2021"

[dependencies]
generics = {path = "../../utils/generics"}
data_types = {path = "../../data_types"}
catalog_schema = {path = "../schema"}
rid = {path = "../../rid"}

strum = "0.26.3"
strum_macros = "0.26.3"
