[workspace]
members = [
    "tools/bpm_bench",

    "crates/common",
    "crates/primer",
    "crates/db_core",
    "crates/stats",
    "crates/data_types",
    "crates/binary_utils",
    "crates/generics",
    "crates/error_utils",
    "crates/data_structures",
    "crates/rid",

    "crates/storage/pages",
    "crates/storage/disk", "crates/recovery/log_manager", "crates/buffer/eviction_policy", "crates/buffer/common", "crates/buffer/manager", "crates/concurrency/transaction/core", "crates/execution/expression", "crates/storage/table/tuple", "crates/hashing/common",
]

[profile.bench]
debug = true
