[workspace]
members = [
    "tools/bpm_bench",
    "crates/common",
    "crates/primer",
    "crates/db_core",
    "crates/stats",
    "crates/data_types",
    "crates/binary_utils",
    "crates/generics",
    "crates/error_utils"
]

[profile.bench]
debug = true
