[workspace]
members = [

    "tools/bpm_bench",
    "crates/buffer",
    "crates/common",
    "crates/primer",
    "crates/recovery",
    "crates/storage",
    "crates/stats",
    "crates/concurrency_shared"]
