[package]
name = "disk_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
pages = { workspace = true }
error_utils = { workspace = true }

parking_lot = { workspace = true }

[dev-dependencies]
tempdir = { workspace = true }
