[package]
name = "disk_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../../common"}
pages = {path = "../pages"}
error_utils = {path = "../../utils/error_utils"}

parking_lot = { version = "0.12.3", features = ["default"] }

[dev-dependencies]
tempdir = "0.3.7"
