[package]
name = "checkpoint_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
db_core = { workspace = true }
recovery_log_manager = { workspace = true }
buffer_pool_manager = { workspace = true }
