[package]
name = "transaction"
version = "0.1.0"
edition = "2021"

[dependencies]

common = { workspace = true }
tuple = { workspace = true }
expression = { workspace = true }
rid = { workspace = true }

atomic = "0.6.0"
bytemuck = "1.18.0"

parking_lot = { workspace = true }
