[package]
name = "catalog_schema"
version = "0.1.0"
edition = "2021"

[dependencies]
data_types = {path = "../../data_types"}
error_utils = {path = "../../utils/error_utils"}


strum = "0.26.3"
strum_macros = "0.26.3"
