[package]
name = "tuple"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
rid = { workspace = true }

catalog_schema = { workspace = true }
data_types = { workspace = true }
