[package]
name = "tuple"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../../../common"}
rid = {path = "../../../rid"}

catalog_schema = {path = "../../../catalog/schema"}
data_types = {path = "../../../data_types"}
