[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
bustub_instance = { path = "../../crates/bustub_instance" }
transaction = {path = "../../crates/concurrency/transaction/core"}


clap = { version = "4.5.16", features = ["derive"] }
