[package]
name = "error_utils_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

[dependencies.syn]
version = "2.0"
features = ["full"]

[dependencies.quote]
version = "1.0"

[dependencies.proc-macro2]
version = "1.0"

[lib]
proc-macro = true
