[package]
name = "recovery_log_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
pages = { workspace = true }
disk_storage = { workspace = true }

parking_lot = { workspace = true }
