[package]
name = "lock_manager"
version = "0.1.0"
edition = "2021"

[dependencies]

common = { workspace = true }
rid = { workspace = true }
transaction = { workspace = true }
parking_lot = { workspace = true }
