[package]
name = "lock_manager"
version = "0.1.0"
edition = "2021"

[dependencies]

common = {path = "../../common"}
rid = {path = "../../rid"}
transaction = {path = "../transaction/core"}
parking_lot = "0.12.3"
