[package]
name = "error_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
thiserror = "1.0.64"

error_utils_derive = { path = "../error_utils_derive" }  # The wrapper crate

