[package]
name = "execution_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.3"

# Profiling
tracy-client = { version = "0.17.3", default-features = false }

db_core = {path = "../../db_core" }
buffer_pool_manager = {path = "../../buffer/manager"}

[profile.bench]
debug = true

[features]
default = []
tracing = ["tracy-client/enable"]
tracing-memory-allocation = ["tracing"]
