name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        env:
          # Uncomment to run the tests in a single thread
          # RUST_TEST_THREADS: 1

          # Show backtrace on panic
          RUST_BACKTRACE: 1

          # Show test print output
          RUST_TEST_NOCAPTURE: 1

          # Print --verbose output
          CARGO_TERM_VERBOSE: true
        run: cargo test
