name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    # Running tests in a single thread as we have thread safety tests and we want to have all the threads available for them
    - name: Run tests
      env:
        RUST_TEST_THREADS: 1
      run: cargo test --verbose -- --nocapture
