name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

  # Check for unused dependencies
  unused_deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unused deps
        uses: bnjbvr/cargo-machete@main


  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        env:
          # Uncomment to run the tests in a single thread
          # RUST_TEST_THREADS: 1

          # Show backtrace on panic
          RUST_BACKTRACE: 1

          # Show test print output
          RUST_TEST_NOCAPTURE: 1

          # Print --verbose output
          CARGO_TERM_VERBOSE: true
        run: cargo test
